"""empty message

Revision ID: 9e0ad40c1c7a
Revises: ad221aea53d7
Create Date: 2017-01-11 20:42:51.477885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e0ad40c1c7a'
down_revision = 'ad221aea53d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bucketlistsitems', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucketlistsitems', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
